# Generated by Django 2.2.2 on 2019-07-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='category name', max_length=33, unique=True)),
                ('type', models.CharField(choices=[('saml', 'SAML'), ('oidc', 'OIDC')], max_length=33)),
            ],
            options={
                'verbose_name': 'Entity Type',
                'verbose_name_plural': 'Entity Type',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='data-idp value, es: namirialid', max_length=33, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('entity_id', models.TextField()),
                ('logo', models.CharField(default='/static//images/no-logo.png', help_text='image or relative path', max_length=254, null=True)),
                ('is_active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unical_discovery_service.EntityType')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
    ]
