# Generated by Django 2.2.2 on 2019-07-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unical_discovery_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='category',
            new_name='type',
        ),
    ]
